language: node_js
node_js:
  - "node"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run build
  - sed -i -e "s/\${BranchName}/$TRAVIS_BRANCH/" ./dist/cloudformation/api-swagger.json
  - npm run package-cloudformation
  - npm run deploy-$TRAVIS_BRANCH
