language: node_js

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install ./api/login/github/token/get/ --prefix=./api/login/github/token/get/
  - npm install ./api/authorizer/ --prefix=./api/authorizer/
  - npm install ./api/projects/put --prefix=./api/projects/put
script:
  - sed -i -e "s/\${BranchName}/$TRAVIS_BRANCH/" ./cloudformation/api-swagger.json
  - sh deploy-$TRAVIS_BRANCH.sh
