language: node_js
node_js:
  - "7"
before_install:
  - pip install --user 'awscli==1.11.79'
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run build
  - npm run package-template
  - npm run deploy-$TRAVIS_BRANCH
