language: node_js

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
  - gulp -v
script:
  - npm run build
  - sed -i -e "s/\${BranchName}/$TRAVIS_BRANCH/" ./dist/cloudformation/api-swagger.json
  - sh deploy-$TRAVIS_BRANCH.sh
