language: node_js
node_js:
  - "node"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run build
  - npm run package-template
  - npm run deploy-$TRAVIS_BRANCH
